name: demo context
on:
 workflow_dispatch:

 env:
   name: shiyas

 jobs: 
   job1:
   runs-on: ubuntu-latest
     steps:
       run: 
           echo "iam shiyas ENV: $hello"
           echo "iam the owner: ${{github.repository }}"
           echo "runner os: ${{ runner.os }}"
           echo "Runner arch: ${{ runner.arch }}"
       
      
