name: demo context
on:
 workflow_dispatch:

 env:
   name: shiyas

 jobs: 
   job1:
   runs-on: ubuntu-latest
    steps:
     - runs: 
              echo "iam shiyas ENV: $hello"
              echo "iam the owner ${ {github.repository }}
              echo "runner os ${{ runner.os }}
              echo "arm ${{${{ runner.arch }}
       
      
